### PR TITLE
fix(validation): supports another flavor of discord url

### LINKED ISSUE #27: Discord URL validation fails for valid url
Webhook urls can apparently come from discord.com and discordapp.com

regexr.com/5ers7

### PR DESCRIPTION
**Pull request by mikemfleming**
resolves #27

### CODE REVIEW

**Review by mazzola — APPROVED** [review]

File: src/components/form/index.js [hunk 1]
```diff
@@ -24,7 +24,7 @@ const useStyles = makeStyles((theme) => ({
 }))
 
 const patterns = {
-    discord: /^https:\/\/discord\.com\/api\/webhooks\//,
+    discord: /^https:\/\/discord(app)*\.com\/api\/webhooks\//,
```
Comment (mazzola) [inline src/components/form/index.js:27]: Interesting. Don't know why discord would have two patterns for webhook URLs but good find.
